### ISSUE TITLE
Trapdoor doesn't close

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/PocketMine-0.13.0#66] opened 2015-11-22 03:23 UTC
Trap Door doesn't close. It moves between the underside, right side (vertical) and top.
![screenshot_2015-11-22-01-20-13](https://cloud.githubusercontent.com/assets/13842405/11321877/4e7e739a-90b7-11e5-8e11-77aca77c6a2c.jpg)
![screenshot_2015-11-22-01-19-50](https://cloud.githubusercontent.com/assets/13842405/11321880/62f4f8bc-90b7-11e5-9952-9cc59de05f09.jpg)
![screenshot_2015-11-22-01-19-46](https://cloud.githubusercontent.com/assets/13842405/11321882/7f2b9c70-90b7-11e5-9884-c266846edb13.jpg)

**Comment by iTzAnTiFTW** [comment] 2015-11-22 03:29
I'll look into it (Try to!)

**Comment by keithkfng** [comment] 2015-11-22 03:33
It's been a problem since 0.12. If it hasn't been fixed, there's an unlikely chance of fixing it in 0.13. The team will look into it and see what we can do.

**Comment by keithkfng** [comment] 2015-11-22 03:36
Team members reference http://docs.pocketmine.net/d1/d5f/classpocketmine_1_1block_1_1_trapdoor.html

**Comment by Driesboy** [comment] 2015-11-22 04:40
Ok pocketmine 1.6 have the same problem

**Comment by keithkfng** [comment] 2015-11-22 04:40
@Driesboy would you mind to check out the new release and see if it works I have a feeling I didn't compile it properly - https://github.com/ImagicalCorp/PocketMine-0.13.0/releases/tag/PM-1.7dev%23136

**Comment by keithkfng** [comment] 2015-11-22 04:41
If I didn't, please download the zip file of this repo and compile the src folder using DevTools and make a pull request thx

**Comment by Driesboy** [comment] 2015-11-22 04:45
No sorry i am not in my home
4 hours and i can test ok

**Comment by ZombiePower** [comment] 2015-11-22 08:54
what do you mean by not closing? it did activate (by the looks in your pic)

**Comment by matcracker** [comment] 2015-11-22 13:32
It's a client bug, check in one singleplayer world, place a trap door, close it, exit the world, rejoin and you can see the trap door is open! Magic! xD

**Comment by matcracker** [comment] 2015-11-22 21:37
Tomorrow I try to fix this issue

**Comment by Rodrigo294X** [comment] 2015-11-22 21:43
OK thank you!!

**Comment by Rodrigo294X** [comment] 2015-11-23 15:18
After of the fix, the trapdoor not is saved in the world. It disappear after 5 seconds or when closing them. And this message appears on the console: [15:06:24] [NOTICE]: [RakLib Thread #7976] Blocked 192.168.2.103 for 5 seconds

**Comment by matcracker** [comment] 2015-11-23 15:33
I'm investigating

**Comment by matcracker** [comment] 2015-11-23 16:52
Sorry but is not a bug releated with trapdoor.

**Closed by matcracker** 2015-11-23 16:52 UTC
Labels: bug, enhancement, help wanted

**Comment by NML32** [comment] 2015-11-23 21:40
Should this issue be reopened Like someone said the trap doors keep disappearing

**Comment by matcracker** [comment] 2015-11-23 21:43
When the RakLib error is fixed I can try to watch if trapdoor remain.
