### ISSUE TITLE
Please fix rakilb thing

### ISSUE THREAD

**Issue by AndreyNazarchuk** [ImagicalCorp/PocketMine-0.13.0#89] opened 2015-11-23 03:33 UTC
Here's the error:
https://forums.pocketmine.net/threads/raklibserver-blocked.12480/

It happens whenever something is done to the player, usually teleport()

**Comment by deotern** [comment] 2015-11-23 09:14
I tested, exist...

**Comment by keithkfng** [comment] 2015-11-23 10:24
Don't get why this critical? It's not crashing the server, is it?

**Comment by AndreyNazarchuk** [comment] 2015-11-23 19:18
This issue is iportant because it makes the server block player for 5
seconds everytime they are teleported., causing them to disconnect from the
game.

**Comment by keithkfng** [comment] 2015-11-23 19:48
Okay... The team will look into this issue.

**Comment by thebigsmileXD** [comment] 2015-11-24 07:07
Nope. Not raklib ;'( i am sure we cant. Happens with slabs mostly.

**Comment by AndreyNazarchuk** [comment] 2015-11-24 07:56
just find the part in the code where RakLib blocks the player for 5 seconds, and comment it out. Though it would be better to see why the teleport() function causes wrong packets to be sent, and fix it.

**Comment by thebigsmileXD** [comment] 2015-11-24 08:04
You cant. Thats the problem. I tried it once because it blocked Rails by Aliuly.. And well.. Didn't work. You see nothing

**Comment by AndreyNazarchuk** [comment] 2015-11-24 08:06
Just fix the teleport issue then, it seems that the server expects a
different set of packets to be sent on teleport than are actually sent.
Please, this is the nuggets issue with 0.13.0 servers rn, if you teleport
the player, it becomes unplayable because they timeout.

**Comment by thebigsmileXD** [comment] 2015-11-24 08:12
Why dont u do it? :D

Maybe the packet is just wrong inside if raklib.. No time to look at it right now, sorry
Any other staff can do it?


> Am 24.11.2015 um 09:06 schrieb Andrey Nazarchuk <notifications@github.com>:
> 
> Just fix the teleport issue then, it seems that the server expects a
> different set of packets to be sent on teleport than are actually sent.
> Please, this is the nuggets issue with 0.13.0 servers rn, if you teleport
> the player, it becomes unplayable because they timeout.

**Comment by deotern** [comment] 2015-11-24 08:26
Well, I turn on the debug, here's the error shown:
24.11 01:25:30 [Server] WARNING RuntimeException: "unpack(): Type n: not enough input, need 2, have 1" (E_WARNING) in "/src/pocketmine/utils/BinaryStream__64bit" at line 213
24.11 01:25:30 [Server] DEBUG Packet pocketmine\network\protocol\ContainerSetSlotPacket 0xb77a0aff00030000
24.11 01:25:30 [Server] DEBUG #11 (1): require_once(string phar:///jar/PocketMine-Deot3.phar/src/pocketmine/PocketMine.php)
24.11 01:25:30 [Server] DEBUG #10 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///jar/PocketMine-Deot3.phar/, string /, string /plugins/)
24.11 01:25:30 [Server] DEBUG #9 /src/pocketmine/Server(1705): pocketmine\Server->start(boolean)
24.11 01:25:30 [Server] DEBUG #8 /src/pocketmine/Server(2104): pocketmine\Server->tickProcessor(boolean)
24.11 01:25:30 [Server] DEBUG #7 /src/pocketmine/Server(2226): pocketmine\Server->tick(boolean)
24.11 01:25:30 [Server] DEBUG #6 /src/pocketmine/Server(2474): pocketmine\network\Network->processInterfaces(boolean)
24.11 01:25:30 [Server] DEBUG #5 /src/pocketmine/network/Network__64bit(159): pocketmine\network\RakLibInterface->process(boolean)
24.11 01:25:30 [Server] DEBUG #4 /src/pocketmine/network/RakLibInterface(81): raklib\server\ServerHandler->handlePacket(boolean)
24.11 01:25:30 [Server] DEBUG #3 /src/raklib/server/ServerHandler__64bit(90): pocketmine\network\RakLibInterface->handleEncapsulated(string 60.49.75.116:17921, raklib\protocol\EncapsulatedPacket `.@........z......, integer 0)
24.11 01:25:30 [Server] DEBUG #2 /src/pocketmine/network/RakLibInterface(139): pocketmine\network\protocol\ContainerSetSlotPacket->decode(boolean)
24.11 01:25:30 [Server] DEBUG #1 /src/pocketmine/network/protocol/ContainerSetSlotPacket(40): pocketmine\utils\BinaryStream->getSlot(boolean)
24.11 01:25:30 [Server] DEBUG #0 /src/pocketmine/utils/BinaryStream__64bit(213): unpack(string n, string .)

**Comment by deotern** [comment] 2015-11-24 08:29
This is shown when Player joined, not teleport... This doesn't happened in previous build, when I tried latest scr build, it happened... So, this prove that someone has merged/done a commit/PR that causes this bug.... :/

**Comment by legoboy0215** [comment] 2015-11-24 11:45
I saw that before.

**Comment by keithkfng** [comment] 2015-11-24 11:46
Saw a commit or...

**Comment by legoboy0215** [comment] 2015-11-24 11:47
The error. And I have an idea why this happens. Look at this:
'ContainerSetSlotPacket'. It has something to do with the packet. Inventory or chest?

**Comment by keithkfng** [comment] 2015-11-24 11:48
Looks more like chest than inventory

**Comment by AndreyNazarchuk** [comment] 2015-11-24 14:52
Guys, Shoghicp did it to try to stop *hackers* from sending packets that
are too short. Just comment out the ralkib line that sends "ip blocked for
5 seconds"  for now...

**Comment by mwvent** [comment] 2015-11-24 14:53
Please see related comment  just left in https://github.com/ImagicalCorp/PocketMine-0.13.0/issues/82 - this bit of code appeared to be generating a lot of RakLib errors creating a ContainerSetContentPacket. It wasn't the ContainerSetContentPacket itself - there are other bits of code that generate it and it works fine just the part I added an abort to in commit https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/d46f555396e440bc8bc027c2a27579afc9ff8b1d

**Comment by AndreyNazarchuk** [comment] 2015-11-24 15:02
Then please fix it.

**Comment by legoboy0215** [comment] 2015-11-25 01:49
It is fixed in the latest build :)

**Comment by AndreyNazarchuk** [comment] 2015-11-25 03:01
No don't close it, its not fixed yet.

**Comment by legoboy0215** [comment] 2015-11-25 05:41
Newest build too!

**Comment by mwvent** [comment] 2015-11-25 08:34
Could you set the debug level to 2 in poketmine.yml. This will show the actual error that is triggering raklib blocks and you can send us it. I haven't been able to reproduce on latest commit - try latest commit rather than build the merge I put in fixes a lot of raklib errors

**Comment by OfficialJoey** [comment] 2015-11-25 10:40
This is also when a person joins

**Comment by mwvent** [comment] 2015-11-25 10:50
Yes if you are using latest release this is to be expected. @legoboy0215 can current master branch be released it seems stable to me

**Comment by keithkfng** [comment] 2015-11-25 10:51
Nah, let @ZombieP0wer fix the crafting and furnace bugs tomorrow. Also some errors while compiling by Travis - https://travis-ci.org/ImagicalCorp/PocketMine-0.13.0

**Comment by mwvent** [comment] 2015-11-25 10:56
Oh yes I didn't see commit https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/2b8a82a6d548f85ebc7228baada1230495b4b87b before I wrote that :-)

**Comment by keithkfng** [comment] 2015-11-25 10:57
Hahaha, yes, he will be attempting to fix those bugs tomorrow

**Comment by keithkfng** [comment] 2015-11-25 11:14
Thunder33345 debugged an error with RakLib here with level 10 - https://forums.pocketmine.net/threads/weird-notice.13193/

**Comment by mwvent** [comment] 2015-11-25 12:11
Oh good that's the error I stopped getting with commit https://github.com/ImagicalCorp/PocketMine-0.13.0/commit/d46f555396e440bc8bc027c2a27579afc9ff8b1d so it shouldn't be a problem with the next release.

**Comment by thebigsmileXD** [comment] 2015-11-25 12:13
I can confirm that, having the same bug in 0.11 also. When you try to select the slot it happens again, 1 more slot

**Comment by AndreyNazarchuk** [comment] 2015-12-04 06:31
Guys I fixed it, it was happening because I did $player->teleport(); without telling it where to teleport. :palm_tree: lol

**Closed** 2015-12-04 06:31 UTC
Labels: Bug, Critical, Enhancement, Help Needed

**Comment by keithkfng** [comment] 2015-12-04 08:07
Can you submit a PR with the fixes @AndreyNazarchuk? Thanks.

**Comment by keithkfng** [comment] 2015-12-04 08:07
If applicable, it was probably your setup configuration problem LOL nothing to do with this

**Comment by deotern** [comment] 2015-12-04 09:01
There's no PR, @AndreyNazarchuk said that he used the API wrongly and caused the problem

**Comment by thebigsmileXD** [comment] 2015-12-04 09:04
But on /teleport ~ ~15 ~15 you also start to bug

**Comment by thebigsmileXD** [comment] 2015-12-23 15:13
Still no fix? This is kind of annoying, just searched through the code and can't find any error..
