### ISSUE TITLE
Skin are all black

### ISSUE THREAD

**Issue by legoboy0215** [ImagicalCorp/PocketMine-0.13.0#14] opened 2015-11-19 11:24 UTC
Ok, this is just a reminder. We are a 3rd-party group who thought helping is nice :) So don't blame all bugs on us. We are trying our best!

**Comment by keithkfng** [comment] 2015-11-19 11:26
Assign @thebigsmileXD, it's a skin data problem I think.

**Comment by thebigsmileXD** [comment] 2015-11-19 13:06
Wait. Black but you can join

**Comment by astersx** [comment] 2015-11-19 16:07
I really hope you can fix all bugs :),  humans learn so not all is fixed in stone :)
P.S. Im mad,  phar file is 0.11

**Comment by Driesboy** [comment] 2015-11-19 19:09
yes you can join 
but the skins are black
![img_1809](https://cloud.githubusercontent.com/assets/15795262/11281126/752eda44-8ef9-11e5-9c83-81c23effaeb1.PNG)

**Comment by keithkfng** [comment] 2015-11-19 19:55
Oh well, we can't fix that ourselves. As @legoboy0215 said, we're just third party! Anyway, at least you can join and play!

**Comment by XFuryMCPE** [comment] 2015-11-19 21:05
Why can't it be fixed..? Everything is possible right?

**Comment by keithkfng** [comment] 2015-11-19 22:40
No, it's something the Imagical Corporation team won't fix at the moment.

**Comment by XFuryMCPE** [comment] 2015-11-20 01:34
It is happening because they added a skin pack with transparent skins

**Comment by mwvent** [comment] 2015-11-20 02:45
OK some observations that may be of interest

On my setup I have been capturing player skin data for quite a while using $player->getSkinData() and saving it to a database.

My website has a render function which converts on the fly the raw skindata to another format for use on dynamic website pages

Here is a player that joined for the first time after 0.13 - the (websites) raw to svg conversion works fine - this means I am reading the same amount of bytes as before to make up the image and it is valid
https://wattz.org.uk/mcpe/skins/?user=neil777&format=svg
https://wattz.org.uk/mcpe/skins/?user=neil777&format=flat

I can grab the source data using the url 
https://wattz.org.uk/mcpe/skins/?user=neil777&format=raw

The data is 16,384 bytes - exactly double what any older skin file was (8192 bytes)

So it seems the extra data is redundant? 

I decided to get the skin data and split it in half
wget "https://wattz.org.uk/mcpe/skins/?user=neil777&format=raw" -O a.skin
split -b 8192 -d a.skin b

Were they a duplicate? Nope
$diff b00 b01
Binary files b00 and b01 differ

I copied them back to the webserver and made two pages to render each half - they are different
https://wattz.org.uk/mcpe/skins/renderb00.php?format=svg
https://wattz.org.uk/mcpe/skins/renderb01.php?format=svg

The extra data is the back of the skin? The skin in reverse? Nope it has structure
https://wattz.org.uk/mcpe/skins/renderb00.php?format=svg&w=180
https://wattz.org.uk/mcpe/skins/renderb00.php?format=flat
https://wattz.org.uk/mcpe/skins/renderb01.php?format=svg&w=180
https://wattz.org.uk/mcpe/skins/renderb01.php?format=flat


After that I thought Id compare two skins that I knew were the same by logging in with a different name myself

The resulting skin data ended up being 8192 bytes long
https://wattz.org.uk/mcpe/skins/?user=SuperMatt1999&format=flat
https://wattz.org.uk/mcpe/skins/?user=SuperMatt1999&format=raw

So does this make sense at all to anybody? What is the extra skin data used for? would finding the code that stores the skin data in memory and forcing it to truncate the data down to 8192 bytes help at all? Hopefully neil777 doesn't change their skin and ruin the examples :-)

I understand ImagicalCorp you guys have your hands full but somebody else may be looking into this and they will be bound to read this issue page. Its a bit low level for me ill try and see if I can have a go myself tomorrow after work too if nobody has any ideas

**Comment by keithkfng** [comment] 2015-11-20 02:49
You can try it, and see if you can submit a PR to help us out.

**Comment by Driesboy** [comment] 2015-11-20 05:47
I have fix it normaly with my pull request

**Comment by thebigsmileXD** [comment] 2015-11-20 05:55
Really neat, man!
I already thought it before
They added the overlays like on pc! I'll try to fix the skin to steve

**Comment by keithkfng** [comment] 2015-11-20 06:26
I thought you said you wouldn't work on it anymore... Anyway, thanks!

**Comment by thebigsmileXD** [comment] 2015-11-20 06:53
xD it would be so easy. I am sure i'll get it to work in no time :)

**Comment by keithkfng** [comment] 2015-11-20 08:32
Skins are now fixed in the latest update. Build #41 will be released with that update, but you can always recompile if you don't want to wait for the build.

**Comment by thebigsmileXD** [comment] 2015-11-20 08:36
Its so annoying i cant try the 0.13 with iphone..

**Comment by keithkfng** [comment] 2015-11-20 08:37
It's out on the App Store, I've got it, why can't you do it?

**Comment by thebigsmileXD** [comment] 2015-11-20 08:38
Germany takes longer to allow updates

**Comment by thebigsmileXD** [comment] 2015-11-20 08:40
xD Okay.. released 1 minute ago :D

**Comment by mwvent** [comment] 2015-11-20 13:21
Thanks @thebigsmileXD :+1:  - Thats a good half done but I am still seeing blank skins in-game. Does this work for others? If not could we re-open the issue?

It looks like data is being received correctly from the client and stored fine (as my plugin can retrieve it)

I'm guessing looking at where references to the getSkinData function are made that the issue is in Player.php when sending the skin to other clients

public function sendFullPlayerListData(Player $p){
                $pk = new PlayerListPacket();
                $pk->type = PlayerListPacket::TYPE_ADD;
                foreach($this->playerList as $player){
                        $pk->entries[] = [$player->getUniqueId(), $player->getId(), $player->getDisplayName(), $player->isSkinSlim(), $player->getSkinData()];
                }

                $p->dataPacket($pk);
        }

or in /pocketmine/network/protocol/PlayerListPacket.php

I want to compare network packets with the ones between two vanilla mcpe clients playing a game to see what the differences are. I downloaded and installed Wireshark and captured the data - I'm a little lost as to how to interpret it however. Wireshark has a native MCPE protocol dissector but it doesn't seem to be making sense of the packets is it outdated somehow? All I see are Types 0x8c, 0xc0 and 0x84 which do not seem to be the network ids documented anywhere?
I also tried https://github.com/brandon15811/MinecraftPE-Dissector/blob/master/mcpe.lua  (had to rename Proto("MCPE" to Proto("MCPE2" so it didnt confilct with builtin dissector and select it on Decode as ) still no luck.

Does anybody already have a link to anything that lets me look at the decoded packets. I'm a bit stuck otherwise without having lower-level knowledge of how the protocol works

**Comment by keithkfng** [comment] 2015-11-20 13:23
Something still happening, skins are still black!

**Comment by PEMapModder** [comment] 2015-11-20 13:30
Because the packets that receive and send skins are wrong.

**Comment by thebigsmileXD** [comment] 2015-11-20 13:45
@PEMapModder is right. We cant fix that so easily

**Comment by PEMapModder** [comment] 2015-11-20 14:01
No, just correct the packet encoding/decoding part.

**Comment by mwvent** [comment] 2015-11-20 14:08
Well I suppose the best place to start is seeing how vanilla clients do it. I'm trying to establish if the built-in support for MCPE in Wireshark is not working or its because I am using it wrong :-)
I think we have established the server receives the data fine it should just be the sending it out to clients to fix

**Comment by mwvent** [comment] 2015-11-20 14:13
https://wattz.org.uk/mcpe/downloads/MCPECap2.pcapng

![pc_screenshot](https://cloud.githubusercontent.com/assets/1349580/11301673/d4ec7878-8f90-11e5-9274-9ea1f55d9055.png)

**Comment by thebigsmileXD** [comment] 2015-11-20 14:20
Yea. Its just the server sending to client part. I know the coding you have in the screenshot. I'll have to so some things now, but i might be able to fix this this evening (15:20 for me right now.).
Thanks alot for the screenshot. I think that won't take me too long

**Comment by mwvent** [comment] 2015-11-20 14:22
@thebigsmileXD - you sir are a genius

**Comment by thebigsmileXD** [comment] 2015-11-20 14:32
Hahaa, thanks, but others are also. Without this team i guess i wouldn't even be able to compile the phars and so on ;) or getting it run!
My server is running for 2 hours now. No crashes so far.

**Comment by Driesboy** [comment] 2015-11-20 15:11
https://github.com/hmy2001/PocketMine-0.13.x
The skins work on this

**Comment by ardaozkal** [comment] 2015-11-20 16:09
How the got that fixed. https://github.com/hmy2001/PocketMine-0.13.x/commit/dd6f201ef4d6a684a862f40ad02abe5a2e60a6b9

**Comment by vvzar** [comment] 2015-11-20 20:21
I made changes provided by hmy2001 using $skinflag in Katana sources, but still skin invalid message. (If I use setskin with steve raw data in hex, and disable checks for packet lengh all works fine and I can join, but thats it.

**Comment by keithkfng** [comment] 2015-11-20 21:20
Updated. Please recompile and try again.

**Comment by thebigsmileXD** [comment] 2015-11-20 22:14
I'll try

**Comment by legoboy0215** [comment] 2015-11-20 23:23
¡Muy bien!

**Comment by jojoe77777** [comment] 2015-11-21 00:01
Leaving some notes:
In 0.13 transparency was added for skins
On MCPC, if you have your skin file blank, it makes your skin black

**Comment by EpicSteve33** [comment] 2015-11-21 07:12
skins still broke lol

**Comment by keithkfng** [comment] 2015-11-21 07:13
Will be fixed in latest build.

**Comment by EpicSteve33** [comment] 2015-11-21 07:15
i just downloaded it and still the same

**Comment by keithkfng** [comment] 2015-11-21 07:16
It's upcoming build, not current build. Sorry about the confusion.

**Comment by EpicSteve33** [comment] 2015-11-21 07:17
when release?

**Comment by Driesboy** [comment] 2015-11-21 09:12
release date please

**Comment by keithkfng** [comment] 2015-11-21 09:13
I can't promise you a release date. There's still some bugs the team wants to fix before making another release. It could take anytime between one day and one week. I don't know.

**Comment by thebigsmileXD** [comment] 2015-11-21 10:10
CANT YOU ALL WAIT?! IT TAKES TIME. IDTOIS

**Comment by ardaozkal** [comment] 2015-11-21 10:14
Calm down lol

**Comment by ardaozkal** [comment] 2015-11-21 10:14
Also people it is true that it takes time to update, test, release, build etc.

**Comment by astersx** [comment] 2015-11-21 10:16
Why insults?

**Comment by thebigsmileXD** [comment] 2015-11-21 10:17
I already have fixed some simple crafting bugs but i also want to play and create my lobby..

**Comment by keithkfng** [comment] 2015-11-21 10:18
Committed here?

**Comment by ZenaGamingsky** [comment] 2015-11-21 11:12
i think this code will fix this

**Comment by ZenaGamingsky** [comment] 2015-11-21 11:12
<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____  
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \ 
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/ 
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_| 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 * 
 *
*/

namespace pocketmine\entity;

use pocketmine\inventory\InventoryHolder;
use pocketmine\inventory\PlayerInventory;
use pocketmine\item\Item as ItemItem;
use pocketmine\network\protocol\PlayerListPacket;
use pocketmine\utils\UUID;
use pocketmine\nbt\NBT;
use pocketmine\nbt\tag\Byte;
use pocketmine\nbt\tag\Compound;
use pocketmine\nbt\tag\Enum;
use pocketmine\nbt\tag\Short;
use pocketmine\nbt\tag\String;
use pocketmine\network\Network;
use pocketmine\network\protocol\AddPlayerPacket;
use pocketmine\network\protocol\RemovePlayerPacket;
use pocketmine\Player;

class Human extends Creature implements ProjectileSource, InventoryHolder{

	const DATA_PLAYER_FLAG_SLEEP = 1;
	const DATA_PLAYER_FLAG_DEAD = 2;

	const DATA_PLAYER_FLAGS = 16;
	const DATA_PLAYER_BED_POSITION = 17;

	protected $nameTag = "TESTIFICATE";
	/** @var PlayerInventory */
	protected $inventory;


	/** @var UUID */
	protected $uuid;
	protected $rawUUID;

	public $width = 0.6;
	public $length = 0.6;
	public $height = 1.8;
	public $eyeHeight = 1.62;

	protected $skin;
	protected $isSlim = false;
	protected $isTransparent = false;

	public function getSkinData(){
		return $this->skin;
	}

	public function isSkinSlim(){
		return $this->isSlim;
	}

	public function isSkinTransparent(){
		return $this->isTransparent;
	}

	/**
	 * @return UUID|null
	 */
	public function getUniqueId(){
		return $this->uuid;
	}

	/**
	 * @return string
	 */
	public function getRawUniqueId(){
		return $this->rawUUID;
	}

	/**
	 * @param string $str
	 * @param bool   $isSlim
	 */
	public function setSkin($str, $isSlim = false, $isTransparent = false){
		$this->skin = $str;
		$this->isSlim = (bool) $isSlim;
		$this->isTransparent = (bool) $isTransparent;
	}

	public function getInventory(){
		return $this->inventory;
	}

	protected function initEntity(){

		$this->setDataFlag(self::DATA_PLAYER_FLAGS, self::DATA_PLAYER_FLAG_SLEEP, false);
		$this->setDataProperty(self::DATA_PLAYER_BED_POSITION, self::DATA_TYPE_POS, [0, 0, 0]);

		$this->inventory = new PlayerInventory($this);
		if($this instanceof Player){
			$this->addWindow($this->inventory, 0);
		}


		if(!($this instanceof Player)){
			if(isset($this->namedtag->NameTag)){
				$this->setNameTag($this->namedtag["NameTag"]);
			}

			if(isset($this->namedtag->Skin) and $this->namedtag->Skin instanceof Compound){
				$this->setSkin($this->namedtag->Skin["Data"], $this->namedtag->Skin["Slim"] > 0);
			}

			$this->uuid = UUID::fromData($this->getId(), $this->getSkinData(), $this->getNameTag());
		}

		if(isset($this->namedtag->Inventory) and $this->namedtag->Inventory instanceof Enum){
			foreach($this->namedtag->Inventory as $item){
				if($item["Slot"] >= 0 and $item["Slot"] < 9){ //Hotbar
					$this->inventory->setHotbarSlotIndex($item["Slot"], isset($item["TrueSlot"]) ? $item["TrueSlot"] : -1);
				}elseif($item["Slot"] >= 100 and $item["Slot"] < 104){ //Armor
					$this->inventory->setItem($this->inventory->getSize() + $item["Slot"] - 100, NBT::getItemHelper($item));
				}else{
					$this->inventory->setItem($item["Slot"] - 9, NBT::getItemHelper($item));
				}
			}
		}

		parent::initEntity();
	}

	public function getName(){
		return $this->getNameTag();
	}

	public function getDrops(){
		$drops = [];
		if($this->inventory !== null){
			foreach($this->inventory->getContents() as $item){
				$drops[] = $item;
			}
		}

		return $drops;
	}

	public function saveNBT(){
		parent::saveNBT();
		$this->namedtag->Inventory = new Enum("Inventory", []);
		$this->namedtag->Inventory->setTagType(NBT::TAG_Compound);
		if($this->inventory !== null){
			for($slot = 0; $slot < 9; ++$slot){
				$hotbarSlot = $this->inventory->getHotbarSlotIndex($slot);
				if($hotbarSlot !== -1){
					$item = $this->inventory->getItem($hotbarSlot);
					if($item->getId() !== 0 and $item->getCount() > 0){
						$this->namedtag->Inventory[$slot] = new Compound(false, [
							new Byte("Count", $item->getCount()),
							new Short("Damage", $item->getDamage()),
							new Byte("Slot", $slot),
							new Byte("TrueSlot", $hotbarSlot),
							new Short("id", $item->getId()),
						]);
						continue;
					}
				}
				$this->namedtag->Inventory[$slot] = new Compound(false, [
					new Byte("Count", 0),
					new Short("Damage", 0),
					new Byte("Slot", $slot),
					new Byte("TrueSlot", -1),
					new Short("id", 0),
				]);
			}

			//Normal inventory
			$slotCount = Player::SURVIVAL_SLOTS + 9;
			//$slotCount = (($this instanceof Player and ($this->gamemode & 0x01) === 1) ? Player::CREATIVE_SLOTS : Player::SURVIVAL_SLOTS) + 9;
			for($slot = 9; $slot < $slotCount; ++$slot){
				$item = $this->inventory->getItem($slot - 9);
				$this->namedtag->Inventory[$slot] = new Compound(false, [
					new Byte("Count", $item->getCount()),
					new Short("Damage", $item->getDamage()),
					new Byte("Slot", $slot),
					new Short("id", $item->getId()),
				]);
			}

			//Armor
			for($slot = 100; $slot < 104; ++$slot){
				$item = $this->inventory->getItem($this->inventory->getSize() + $slot - 100);
				if($item instanceof ItemItem and $item->getId() !== ItemItem::AIR){
					$this->namedtag->Inventory[$slot] = new Compound(false, [
						new Byte("Count", $item->getCount()),
						new Short("Damage", $item->getDamage()),
						new Byte("Slot", $slot),
						new Short("id", $item->getId()),
					]);
				}
			}
		}
	}

	public function spawnTo(Player $player){
		if($player !== $this and !isset($this->hasSpawned[$player->getId()])){
			$this->hasSpawned[$player->getId()] = $player;

//			if(strlen($this->skin) < 64 * 32 * 4){
//				$this->server->getLogger()->info((new \ReflectionClass($this))->getShortName() . " must have a valid skin set");
//			}


			if(!($this instanceof Player)){
				$this->server->updatePlayerListData($this->getUniqueId(), $this->getId(), $this->getName(), $this->isSlim, $this->isTransparent, $this->skin, [$player]);
			}

			$pk = new PlayerListPacket();
			$pk->type = PlayerListPacket::TYPE_ADD;
			$pk->entries[] = [$this->getUniqueId(), $this->getId(), $this->getName(), $this->isSlim, $this->isTransparent, $this->skin];
			$player->dataPacket($pk);

			$pk = new AddPlayerPacket();
			$pk->uuid = $this->getUniqueId();
			$pk->username = $this->getName();
			$pk->eid = $this->getId();
			$pk->x = $this->x;
			$pk->y = $this->y;
			$pk->z = $this->z;
			$pk->speedX = $this->motionX;
			$pk->speedY = $this->motionY;
			$pk->speedZ = $this->motionZ;
			$pk->yaw = $this->yaw;
			$pk->pitch = $this->pitch;
			$pk->item = $this->getInventory()->getItemInHand();
			$pk->metadata = $this->dataProperties;
			$player->dataPacket($pk);

			$this->inventory->sendArmorContents($player);

			if(!($this instanceof Player)){
				$this->server->removePlayerListData($this->getUniqueId(), [$player]);
			}
		}
	}

	public function despawnFrom(Player $player){
		if(isset($this->hasSpawned[$player->getId()])){

			$pk = new RemovePlayerPacket();
			$pk->eid = $this->getId();
			$pk->clientId = $this->getUniqueId();
			$player->dataPacket($pk);
			unset($this->hasSpawned[$player->getId()]);
		}
	}

	public function close(){
		if(!$this->closed){
			if(!($this instanceof Player) or $this->loggedIn){
				foreach($this->inventory->getViewers() as $viewer){
					$viewer->removeWindow($this->inventory);
				}
			}
			parent::close();
		}
	}

}

**Comment by Driesboy** [comment] 2015-11-21 11:13
Create pull request

**Comment by legoboy0215** [comment] 2015-11-21 11:18
I think. And you don't have good reputation.

**Comment by Driesboy** [comment] 2015-11-21 11:37
I

**Comment by keithkfng** [comment] 2015-11-21 11:39
Anyone got a fix?

**Comment by Driesboy** [comment] 2015-11-21 11:40
ZenaGamingsky Have fix it 
but he removed it

**Comment by keithkfng** [comment] 2015-11-21 11:42
Hmm...

**Comment by DRedDogPE** [comment] 2015-11-21 11:42
I have it in my email 
lemmie get it

**Comment by Driesboy** [comment] 2015-11-21 11:43
THIS maybe 
https://github.com/hmy2001/PocketMine-0.13.x/commit/dd6f201ef4d6a684a862f40ad02abe5a2e60a6b9

**Comment by keithkfng** [comment] 2015-11-21 11:43
Good, please commit it and see how we go

**Comment by DRedDogPE** [comment] 2015-11-21 11:44
```php
<?php

/*
*

    ____ _ _ __ __ _ __ __ ____
    | _ \ ___ | | __| || \/ ()_ __ ___ | \/ | _ \
    | |) / _ \ / _| |/ / _ \ | |\/| | | '_ \ / _ ___| |\/| | |_) |
    | / (_) | (| < / || | | | | | | | _/___| | | | __/
    || __/ ___||\___|__|| |||| ||__| || ||_| *
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version. *
    @author PocketMine Team
    @link http://www.pocketmine.net/
    * */

namespace pocketmine\entity;

use pocketmine\inventory\InventoryHolder;
use pocketmine\inventory\PlayerInventory;
use pocketmine\item\Item as ItemItem;
use pocketmine\network\protocol\PlayerListPacket;
use pocketmine\utils\UUID;
use pocketmine\nbt\NBT;
use pocketmine\nbt\tag\Byte;
use pocketmine\nbt\tag\Compound;
use pocketmine\nbt\tag\Enum;
use pocketmine\nbt\tag\Short;
use pocketmine\nbt\tag\String;
use pocketmine\network\Network;
use pocketmine\network\protocol\AddPlayerPacket;
use pocketmine\network\protocol\RemovePlayerPacket;
use pocketmine\Player;

class Human extends Creature implements ProjectileSource, InventoryHolder{

const DATA_PLAYER_FLAG_SLEEP = 1;
const DATA_PLAYER_FLAG_DEAD = 2;

const DATA_PLAYER_FLAGS = 16;
const DATA_PLAYER_BED_POSITION = 17;

protected $nameTag = "TESTIFICATE";
/** @var PlayerInventory */
protected $inventory;


/** @var UUID */
protected $uuid;
protected $rawUUID;

public $width = 0.6;
public $length = 0.6;
public $height = 1.8;
public $eyeHeight = 1.62;

protected $skin;
protected $isSlim = false;
protected $isTransparent = false;

public function getSkinData(){
    return $this->skin;
}

public function isSkinSlim(){
    return $this->isSlim;
}

public function isSkinTransparent(){
    return $this->isTransparent;
}

/**
 * @return UUID|null
 */
public function getUniqueId(){
    return $this->uuid;
}

/**
 * @return string
 */
public function getRawUniqueId(){
    return $this->rawUUID;
}

/**
 * @param string $str
 * @param bool   $isSlim
 */
public function setSkin($str, $isSlim = false, $isTransparent = false){
    $this->skin = $str;
    $this->isSlim = (bool) $isSlim;
    $this->isTransparent = (bool) $isTransparent;
}

public function getInventory(){
    return $this->inventory;
}

protected function initEntity(){

    $this->setDataFlag(self::DATA_PLAYER_FLAGS, self::DATA_PLAYER_FLAG_SLEEP, false);
    $this->setDataProperty(self::DATA_PLAYER_BED_POSITION, self::DATA_TYPE_POS, [0, 0, 0]);

    $this->inventory = new PlayerInventory($this);
    if($this instanceof Player){
        $this->addWindow($this->inventory, 0);
    }


    if(!($this instanceof Player)){
        if(isset($this->namedtag->NameTag)){
            $this->setNameTag($this->namedtag["NameTag"]);
        }

        if(isset($this->namedtag->Skin) and $this->namedtag->Skin instanceof Compound){
            $this->setSkin($this->namedtag->Skin["Data"], $this->namedtag->Skin["Slim"] > 0);
        }

        $this->uuid = UUID::fromData($this->getId(), $this->getSkinData(), $this->getNameTag());
    }

    if(isset($this->namedtag->Inventory) and $this->namedtag->Inventory instanceof Enum){
        foreach($this->namedtag->Inventory as $item){
            if($item["Slot"] >= 0 and $item["Slot"] < 9){ //Hotbar
                $this->inventory->setHotbarSlotIndex($item["Slot"], isset($item["TrueSlot"]) ? $item["TrueSlot"] : -1);
            }elseif($item["Slot"] >= 100 and $item["Slot"] < 104){ //Armor
                $this->inventory->setItem($this->inventory->getSize() + $item["Slot"] - 100, NBT::getItemHelper($item));
            }else{
                $this->inventory->setItem($item["Slot"] - 9, NBT::getItemHelper($item));
            }
        }
    }

    parent::initEntity();
}

public function getName(){
    return $this->getNameTag();
}

public function getDrops(){
    $drops = [];
    if($this->inventory !== null){
        foreach($this->inventory->getContents() as $item){
            $drops[] = $item;
        }
    }

    return $drops;
}

public function saveNBT(){
    parent::saveNBT();
    $this->namedtag->Inventory = new Enum("Inventory", []);
    $this->namedtag->Inventory->setTagType(NBT::TAG_Compound);
    if($this->inventory !== null){
        for($slot = 0; $slot < 9; ++$slot){
            $hotbarSlot = $this->inventory->getHotbarSlotIndex($slot);
            if($hotbarSlot !== -1){
                $item = $this->inventory->getItem($hotbarSlot);
                if($item->getId() !== 0 and $item->getCount() > 0){
                    $this->namedtag->Inventory[$slot] = new Compound(false, [
                        new Byte("Count", $item->getCount()),
                        new Short("Damage", $item->getDamage()),
                        new Byte("Slot", $slot),
                        new Byte("TrueSlot", $hotbarSlot),
                        new Short("id", $item->getId()),
                    ]);
                    continue;
                }
            }
            $this->namedtag->Inventory[$slot] = new Compound(false, [
                new Byte("Count", 0),
                new Short("Damage", 0),
                new Byte("Slot", $slot),
                new Byte("TrueSlot", -1),
                new Short("id", 0),
            ]);
        }

        //Normal inventory
        $slotCount = Player::SURVIVAL_SLOTS + 9;
        //$slotCount = (($this instanceof Player and ($this->gamemode & 0x01) === 1) ? Player::CREATIVE_SLOTS : Player::SURVIVAL_SLOTS) + 9;
        for($slot = 9; $slot < $slotCount; ++$slot){
            $item = $this->inventory->getItem($slot - 9);
            $this->namedtag->Inventory[$slot] = new Compound(false, [
                new Byte("Count", $item->getCount()),
                new Short("Damage", $item->getDamage()),
                new Byte("Slot", $slot),
                new Short("id", $item->getId()),
            ]);
        }

        //Armor
        for($slot = 100; $slot < 104; ++$slot){
            $item = $this->inventory->getItem($this->inventory->getSize() + $slot - 100);
            if($item instanceof ItemItem and $item->getId() !== ItemItem::AIR){
                $this->namedtag->Inventory[$slot] = new Compound(false, [
                    new Byte("Count", $item->getCount()),
                    new Short("Damage", $item->getDamage()),
                    new Byte("Slot", $slot),
                    new Short("id", $item->getId()),
                ]);
            }
        }
    }
}

public function spawnTo(Player $player){
    if($player !== $this and !isset($this->hasSpawned[$player->getId()])){
        $this->hasSpawned[$player->getId()] = $player;

// if(strlen($this->skin) < 64 * 32 * 4){
// $this->server->getLogger()->info((new \ReflectionClass($this))->getShortName() . " must have a valid skin set");
// }

        if(!($this instanceof Player)){
            $this->server->updatePlayerListData($this->getUniqueId(), $this->getId(), $this->getName(), $this->isSlim, $this->isTransparent, $this->skin, [$player]);
        }

        $pk = new PlayerListPacket();
        $pk->type = PlayerListPacket::TYPE_ADD;
        $pk->entries[] = [$this->getUniqueId(), $this->getId(), $this->getName(), $this->isSlim, $this->isTransparent, $this->skin];
        $player->dataPacket($pk);

        $pk = new AddPlayerPacket();
        $pk->uuid = $this->getUniqueId();
        $pk->username = $this->getName();
        $pk->eid = $this->getId();
        $pk->x = $this->x;
        $pk->y = $this->y;
        $pk->z = $this->z;
        $pk->speedX = $this->motionX;
        $pk->speedY = $this->motionY;
        $pk->speedZ = $this->motionZ;
        $pk->yaw = $this->yaw;
        $pk->pitch = $this->pitch;
        $pk->item = $this->getInventory()->getItemInHand();
        $pk->metadata = $this->dataProperties;
        $player->dataPacket($pk);

        $this->inventory->sendArmorContents($player);

        if(!($this instanceof Player)){
            $this->server->removePlayerListData($this->getUniqueId(), [$player]);
        }
    }
}

public function despawnFrom(Player $player){
    if(isset($this->hasSpawned[$player->getId()])){

        $pk = new RemovePlayerPacket();
        $pk->eid = $this->getId();
        $pk->clientId = $this->getUniqueId();
        $player->dataPacket($pk);
        unset($this->hasSpawned[$player->getId()]);
    }
}

public function close(){
    if(!$this->closed){
        if(!($this instanceof Player) or $this->loggedIn){
            foreach($this->inventory->getViewers() as $viewer){
                $viewer->removeWindow($this->inventory);
            }
        }
        parent::close();
    }
}
```

**Comment by keithkfng** [comment] 2015-11-21 11:44
Commit it please :P

**Comment by DRedDogPE** [comment] 2015-11-21 11:45
ok

**Comment by keithkfng** [comment] 2015-11-21 11:46
Can you also recompile and make it a new release? The build number should be the same as the number of commits at the time of the release. Thanks!

**Comment by ZenaGamingsky** [comment] 2015-11-21 12:35
hi i have a chest fix

**Comment by ZenaGamingsky** [comment] 2015-11-21 12:35
do you want the code

**Comment by SirGamer** [comment] 2015-11-21 14:53
Make a commit.

**Comment by Driesboy** [comment] 2015-11-21 15:38
Yes make a pull request

**Comment by Driesboy** [comment] 2015-11-21 17:23
https://github.com/AkeKy/PocketMine_0.13/commit/8e8b5586a570dd466efc0ab657773e5ebe046472 
Fix

**Comment by thebigsmileXD** [comment] 2015-11-22 21:48
Is it fixed? Transparent skins like in the latest snapshot of pc (1.9) or just the new skin format like 1.8?

**Comment by PEMapModder** [comment] 2015-11-23 07:56
https://github.com/PocketMine/PocketMine-MP/tree/mcpe-0.13

**Comment by thebigsmileXD** [comment] 2015-11-23 08:15
@PEMapModder 404

**Comment by PEMapModder** [comment] 2015-11-23 10:32
sorry updated the link

**Comment by NML32** [comment] 2015-11-24 02:08
Skins seem to be working now. Skins aren't black anymore.

**Closed** 2015-11-24 02:37 UTC
Labels: bug, help wanted, Possibly Fixed

**Comment by legoboy0215** [comment] 2015-11-24 05:23
Yep. But I am not going to use it on my server :P I still use the oldest version. Works great.

**Comment by keithkfng** [comment] 2015-11-24 05:49
Really? I find the latest version better XD

**Comment by thebigsmileXD** [comment] 2015-11-24 05:49
High 5! I use 0.11 still

**Comment by keithkfng** [comment] 2015-11-24 05:49
...

**Comment by legoboy0215** [comment] 2015-11-24 05:51
Latest XD Shovel bugs

**Comment by keithkfng** [comment] 2015-11-24 05:51
Still... Nobody has fixed it

**Comment by keithkfng** [comment] 2015-11-24 05:53
@legoboy0215 https://travis-ci.org/ImagicalCorp/PocketMine-0.13.0/builds three errors with redstone you committed...

**Comment by thebigsmileXD** [comment] 2015-11-24 06:49
Fixed litredstonelamp i guess. Cant find the other classes.

**Comment by keithkfng** [comment] 2015-11-24 06:50
Will see if it works with Travis

**Comment by keithkfng** [comment] 2015-11-24 06:52
Congratulations - it passed! Lel

**Comment by legoboy0215** [comment] 2015-11-24 06:55
@keithkfng It did pass. Not my error :P

**Comment by keithkfng** [comment] 2015-11-24 06:58
Oh really? Lel

**Comment by thebigsmileXD** [comment] 2015-11-24 07:01
Where are the other classes? I know the error. Always the same

**Comment by keithkfng** [comment] 2015-11-24 07:03
Redstone branch - commit the same changes you made to master to that branch please.
